image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - 'python3 -m venv venv'
  - 'source venv/bin/activate'
  - 'pip install --upgrade pip'
  - 'pip install -r ./docs-server/requirements.txt'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '.cache/pip'

pages:
  stage: deploy
  variables:
    ENABLE_PDF_EXPORT: 1
  script:
    - 'source venv/bin/activate'
    - 'mkdocs build --verbose --site-dir public'
    - 'ls -la public'  # Debugging line to check contents
  artifacts:
    when: on_success
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
